// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgywxscmyhdxpctrqzvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndneXd4c2NteWhkeHBjdHJxenZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNTUzMDgsImV4cCI6MjA2ODczMTMwOH0.ue0r1G0z8YHX2OfzgrXvE3rsLaZd3qUCT0v63HrDqLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});